# Przedstawienie 5 najniebezpieczniejszych czynników wypadków pod względem śmiertelności w NY

## Wczytywanie danych z pliku CSV

In [1]:
import pandas as pd
import numpy as np

import requests

nypd_df = pd.read_csv("/home/student/nypd-motor-vehicle-collisions.csv")
nypd_df

/tmp/ipykernel_87204/3460021377.py:6: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  nypd_df = pd.read_csv("/home/student/nypd-motor-vehicle-collisions.csv")

,ACCIDENT DATE,ACCIDENT TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
0,2019-08-05T00:00:00.000,16:30,QUEENS,11434.0,40.676052,-73.790184,"{'type': 'Point', 'coordinates': [-73.790184, ...",NaN,NaN,150-08 123 AVENUE,...,Unspecified,NaN,NaN,NaN,4184637,Sedan,Pick-up Truck,NaN,NaN,NaN
1,2019-08-27T00:00:00.000,16:02,BROOKLYN,11225.0,40.657780,-73.951096,"{'type': 'Point', 'coordinates': [-73.951096, ...",NaN,NaN,288 HAWTHORNE STREET,...,Unspecified,NaN,NaN,NaN,4195773,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
2,2019-08-15T00:00:00.000,17:57,MANHATTAN,10002.0,40.718143,-73.993835,"{'type': 'Point', 'coordinates': [-73.993835, ...",CHRYSTIE STREET,GRAND STREET,NaN,...,NaN,NaN,NaN,NaN,4202457,Sedan,NaN,NaN,NaN,NaN
3,2019-08-30T00:00:00.000,21:53,BRONX,10460.0,40.840534,-73.866610,"{'type': 'Point', 'coordinates': [-73.86661, 4...",NaN,NaN,1837 EAST TREMONT AVENUE,...,Unspecified,NaN,NaN,NaN,4198749,Taxi,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
4,2019-08-06T00:00:00.000,9:45,MANHATTAN,10016.0,40.745440,-73.975400,"{'type': 'Point', 'coordinates': [-73.9754, 40...",EAST 35 STREET,2 AVENUE,NaN,...,Driver Inattention/Distraction,NaN,NaN,NaN,4183798,Station Wagon/Sport Utility Vehicle,Bike,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1612173,2012-07-21T00:00:00.000,22:46,BROOKLYN,11226.0,40.651741,-73.965241,"{'type': 'Point', 'coordinates': [-73.9652409,...",PARADE PLACE,CROOKE AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,147595,SPORT UTILITY / STATION WAGON,UNKNOWN,NaN,NaN,NaN
1612174,2012-07-09T00:00:00.000,16:45,NaN,NaN,NaN,NaN,NaN,EDWARD L GRANT HIGHWAY,WEST 169 STREET,NaN,...,Fatigued/Drowsy,Unspecified,NaN,NaN,85220,PASSENGER VEHICLE,LIVERY VEHICLE,PASSENGER VEHICLE,NaN,NaN
1612175,2012-07-09T00:00:00.000,14:35,NaN,NaN,40.791492,-73.935763,"{'type': 'Point', 'coordinates': [-73.935763, ...",NaN,NaN,NaN,...,Unspecified,NaN,NaN,NaN,2853431,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
1612176,2012-07-18T00:00:00.000,9:20,MANHATTAN,10024.0,40.779479,-73.973573,"{'type': 'Point', 'coordinates': [-73.9735729,...",CENTRAL PARK WEST,WEST 77 STREET,NaN,...,Unspecified,Unspecified,NaN,NaN,52405,SPORT UTILITY / STATION WAGON,VAN,BUS,NaN,NaN
1612177,2012-07-12T00:00:00.000,3:10,QUEENS,11361.0,40.762501,-73.782522,"{'type': 'Point', 'coordinates': [-73.7825216,...",39 AVENUE,203 STREET,NaN,...,NaN,NaN,NaN,NaN,259445,PASSENGER VEHICLE,NaN,NaN,NaN,NaN

##### Wczytanie tabeli ze wszytskimi danymi do analizy czynników wypadków w NY

## Wyznaczenie kolumn z niebezpiecznymi czynnikami wypadków, osób poszkodowanych oraz ich śmiertelnością

In [2]:
Selected_data_columns = nypd_df[['NUMBER OF PERSONS KILLED','CONTRIBUTING FACTOR VEHICLE 1','CONTRIBUTING FACTOR VEHICLE 2','CONTRIBUTING FACTOR VEHICLE 3','CONTRIBUTING FACTOR VEHICLE 4','CONTRIBUTING FACTOR VEHICLE 5']]
Selected_data_columns

,NUMBER OF PERSONS KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5
0,0.0,Passing Too Closely,Unspecified,NaN,NaN,NaN
1,0.0,Passing Too Closely,Unspecified,NaN,NaN,NaN
2,0.0,Driver Inattention/Distraction,NaN,NaN,NaN,NaN
3,0.0,Unspecified,Unspecified,NaN,NaN,NaN
4,0.0,Driver Inattention/Distraction,Driver Inattention/Distraction,NaN,NaN,NaN
...,...,...,...,...,...,...
1612173,0.0,Traffic Control Disregarded,Unspecified,NaN,NaN,NaN
1612174,0.0,Fatigued/Drowsy,Fatigued/Drowsy,Unspecified,NaN,NaN
1612175,0.0,Fatigued/Drowsy,Unspecified,NaN,NaN,NaN
1612176,0.0,Driver Inattention/Distraction,Unspecified,Unspecified,NaN,NaN
1612177,0.0,Unspecified,NaN,NaN,NaN,NaN

##### Kolumna z danymi do określenia 5 czynników wypadków oraz ich śmiertelność w NY

## Usunięcie wierszy, które w kolumnach osób zabitych mają nieokreśloną wartość (NaN)

In [3]:
nypd_factors = Selected_data_columns.dropna(subset=['NUMBER OF PERSONS KILLED'])
nypd_factors

,NUMBER OF PERSONS KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5
0,0.0,Passing Too Closely,Unspecified,NaN,NaN,NaN
1,0.0,Passing Too Closely,Unspecified,NaN,NaN,NaN
2,0.0,Driver Inattention/Distraction,NaN,NaN,NaN,NaN
3,0.0,Unspecified,Unspecified,NaN,NaN,NaN
4,0.0,Driver Inattention/Distraction,Driver Inattention/Distraction,NaN,NaN,NaN
...,...,...,...,...,...,...
1612173,0.0,Traffic Control Disregarded,Unspecified,NaN,NaN,NaN
1612174,0.0,Fatigued/Drowsy,Fatigued/Drowsy,Unspecified,NaN,NaN
1612175,0.0,Fatigued/Drowsy,Unspecified,NaN,NaN,NaN
1612176,0.0,Driver Inattention/Distraction,Unspecified,Unspecified,NaN,NaN
1612177,0.0,Unspecified,NaN,NaN,NaN,NaN

##### Oczyszczona tabela z niepotrzebnych(nieokreślonych) wartości

## Dodanie kolumny z czynnikiem wypadków

In [4]:
nypd_factors['CONTRIBUTING FACTORS'] = nypd_factors[['CONTRIBUTING FACTOR VEHICLE 1', 'CONTRIBUTING FACTOR VEHICLE 2', 'CONTRIBUTING FACTOR VEHICLE 3', 'CONTRIBUTING FACTOR VEHICLE 4', 'CONTRIBUTING FACTOR VEHICLE 5']].values.tolist()
nypd_factors

/tmp/ipykernel_87204/2732455402.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nypd_factors['CONTRIBUTING FACTORS'] = nypd_factors[['CONTRIBUTING FACTOR VEHICLE 1', 'CONTRIBUTING FACTOR VEHICLE 2', 'CONTRIBUTING FACTOR VEHICLE 3', 'CONTRIBUTING FACTOR VEHICLE 4', 'CONTRIBUTING FACTOR VEHICLE 5']].values.tolist()

,NUMBER OF PERSONS KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,CONTRIBUTING FACTORS
0,0.0,Passing Too Closely,Unspecified,NaN,NaN,NaN,"[Passing Too Closely, Unspecified, nan, nan, nan]"
1,0.0,Passing Too Closely,Unspecified,NaN,NaN,NaN,"[Passing Too Closely, Unspecified, nan, nan, nan]"
2,0.0,Driver Inattention/Distraction,NaN,NaN,NaN,NaN,"[Driver Inattention/Distraction, nan, nan, nan..."
3,0.0,Unspecified,Unspecified,NaN,NaN,NaN,"[Unspecified, Unspecified, nan, nan, nan]"
4,0.0,Driver Inattention/Distraction,Driver Inattention/Distraction,NaN,NaN,NaN,"[Driver Inattention/Distraction, Driver Inatte..."
...,...,...,...,...,...,...,...
1612173,0.0,Traffic Control Disregarded,Unspecified,NaN,NaN,NaN,"[Traffic Control Disregarded, Unspecified, nan..."
1612174,0.0,Fatigued/Drowsy,Fatigued/Drowsy,Unspecified,NaN,NaN,"[Fatigued/Drowsy, Fatigued/Drowsy, Unspecified..."
1612175,0.0,Fatigued/Drowsy,Unspecified,NaN,NaN,NaN,"[Fatigued/Drowsy, Unspecified, nan, nan, nan]"
1612176,0.0,Driver Inattention/Distraction,Unspecified,Unspecified,NaN,NaN,"[Driver Inattention/Distraction, Unspecified, ..."
1612177,0.0,Unspecified,NaN,NaN,NaN,NaN,"[Unspecified, nan, nan, nan, nan]"

##### Dodanie kolumny z czynnikiem wypadków, wynikająca z połączenia wartości z 5 kolumn z czynnikami wypadków dla pojazdów 1,2,3,4,5

## Wyznaczenie kolumn potrzebnych do dalszej analizy

In [5]:
df = nypd_factors[['NUMBER OF PERSONS KILLED', "CONTRIBUTING FACTORS"]]
df

,NUMBER OF PERSONS KILLED,CONTRIBUTING FACTORS
0,0.0,"[Passing Too Closely, Unspecified, nan, nan, nan]"
1,0.0,"[Passing Too Closely, Unspecified, nan, nan, nan]"
2,0.0,"[Driver Inattention/Distraction, nan, nan, nan..."
3,0.0,"[Unspecified, Unspecified, nan, nan, nan]"
4,0.0,"[Driver Inattention/Distraction, Driver Inatte..."
...,...,...
1612173,0.0,"[Traffic Control Disregarded, Unspecified, nan..."
1612174,0.0,"[Fatigued/Drowsy, Fatigued/Drowsy, Unspecified..."
1612175,0.0,"[Fatigued/Drowsy, Unspecified, nan, nan, nan]"
1612176,0.0,"[Driver Inattention/Distraction, Unspecified, ..."
1612177,0.0,"[Unspecified, nan, nan, nan, nan]"

##### Została utworzona tabela z kolumną osób zabitych oraz czynnikami wypadków

## Zamiana wartości 0 w kolumnie z osobami zabitymi na wartość NaN, a następnie usunięcie tych wartości, gdyż nie będą one potrzebne do dalszej analizy

In [6]:
df['NUMBER OF PERSONS KILLED'] = df['NUMBER OF PERSONS KILLED'].replace(0, np.nan)
df

/tmp/ipykernel_87204/347875460.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['NUMBER OF PERSONS KILLED'] = df['NUMBER OF PERSONS KILLED'].replace(0, np.nan)

,NUMBER OF PERSONS KILLED,CONTRIBUTING FACTORS
0,NaN,"[Passing Too Closely, Unspecified, nan, nan, nan]"
1,NaN,"[Passing Too Closely, Unspecified, nan, nan, nan]"
2,NaN,"[Driver Inattention/Distraction, nan, nan, nan..."
3,NaN,"[Unspecified, Unspecified, nan, nan, nan]"
4,NaN,"[Driver Inattention/Distraction, Driver Inatte..."
...,...,...
1612173,NaN,"[Traffic Control Disregarded, Unspecified, nan..."
1612174,NaN,"[Fatigued/Drowsy, Fatigued/Drowsy, Unspecified..."
1612175,NaN,"[Fatigued/Drowsy, Unspecified, nan, nan, nan]"
1612176,NaN,"[Driver Inattention/Distraction, Unspecified, ..."
1612177,NaN,"[Unspecified, nan, nan, nan, nan]"

In [7]:
df = df.dropna(subset=['NUMBER OF PERSONS KILLED'])
df

,NUMBER OF PERSONS KILLED,CONTRIBUTING FACTORS
7,1.0,"[Unsafe Speed, Unspecified, nan, nan, nan]"
467,1.0,"[Failure to Yield Right-of-Way, nan, nan, nan,..."
540,1.0,"[Reaction to Uninvolved Vehicle, Unspecified, ..."
708,1.0,"[Unsafe Speed, Unspecified, Unspecified, nan, ..."
911,1.0,"[Driver Inattention/Distraction, nan, nan, nan..."
...,...,...
1608873,1.0,"[Aggressive Driving/Road Rage, Unspecified, na..."
1609027,1.0,"[Unspecified, nan, nan, nan, nan]"
1610433,1.0,"[View Obstructed/Limited, Unspecified, nan, na..."
1610994,1.0,"[Alcohol Involvement, Unspecified, nan, nan, nan]"
1611807,1.0,"[Unspecified, Unspecified, nan, nan, nan]"

##### Oczyszczona tabela danych z conajmniej jedną ofiarą wypadków w NY

## Przypisanie ofiary do każdego z czynników wypadków

In [8]:
df_exploded = df.explode('CONTRIBUTING FACTORS')
df_exploded

         NUMBER OF PERSONS KILLED CONTRIBUTING FACTORS
7                             1.0         Unsafe Speed
7                             1.0          Unspecified
7                             1.0                  NaN
7                             1.0                  NaN
7                             1.0                  NaN
...                           ...                  ...
1611807                       1.0          Unspecified
1611807                       1.0          Unspecified
1611807                       1.0                  NaN
1611807                       1.0                  NaN
1611807                       1.0                  NaN

[9185 rows x 2 columns]

##### Za pomocą metody explode, każdy czynnik wypadku został przypisany do ofiary

## Usunięcie wartości NaN z czynników wypadków

In [9]:
df_exploded_drop = df_exploded.dropna()
df_exploded_drop

         NUMBER OF PERSONS KILLED            CONTRIBUTING FACTORS
7                             1.0                    Unsafe Speed
7                             1.0                     Unspecified
467                           1.0   Failure to Yield Right-of-Way
540                           1.0  Reaction to Uninvolved Vehicle
540                           1.0                     Unspecified
...                           ...                             ...
1610433                       1.0                     Unspecified
1610994                       1.0             Alcohol Involvement
1610994                       1.0                     Unspecified
1611807                       1.0                     Unspecified
1611807                       1.0                     Unspecified

[2893 rows x 2 columns]

##### Oczyszczona tabela danych z pustych wartości dla czynników wypadków

## Zsumowanie liczby osób zabitych do poszczególnego czynnika wypadku

In [10]:
person_of_killed = df_exploded_drop.groupby(['CONTRIBUTING FACTORS'])['NUMBER OF PERSONS KILLED'].sum()
person_of_killed

CONTRIBUTING FACTORS
Aggressive Driving/Road Rage                               11.0
Alcohol Involvement                                        61.0
Backing Unsafely                                           28.0
Driver Inattention/Distraction                            268.0
Driver Inexperience                                        24.0
Driverless/Runaway Vehicle                                  1.0
Drugs (Illegal)                                             2.0
Drugs (illegal)                                             4.0
Failure to Keep Right                                       3.0
Failure to Yield Right-of-Way                             189.0
Fatigued/Drowsy                                             3.0
Fell Asleep                                                13.0
Following Too Closely                                      24.0
Glare                                                       1.0
Illnes                                                     33.0
Lost Consciousness                                         23.0
Obstruction/Debris                                          3.0
Other Electronic Device                                     4.0
Other Lighting Defects                                      1.0
Other Vehicular                                            42.0
Outside Car Distraction                                     5.0
Oversized Vehicle                                           1.0
Passenger Distraction                                      53.0
Passing Too Closely                                         2.0
Passing or Lane Usage Improper                             19.0
Pavement Defective                                         10.0
Pavement Slippery                                           9.0
Pedestrian/Bicyclist/Other Pedestrian Error/Confusion      64.0
Physical Disability                                        43.0
Prescription Medication                                     7.0
Reaction to Uninvolved Vehicle                             10.0
Tire Failure/Inadequate                                     3.0
Tow Hitch Defective                                         1.0
Traffic Control Disregarded                               182.0
Turning Improperly                                         16.0
Unsafe Lane Changing                                        2.0
Unsafe Speed                                              156.0
Unspecified                                              1750.0
View Obstructed/Limited                                    17.0
Name: NUMBER OF PERSONS KILLED, dtype: float64

##### Tabela zawierającą zsumowaną liczbę ofiar dla każdego z czynnika wypadku

## Wyznaczenie 5 czynników, w których najcześciej występują ofiary śmiertelne wypadków w NY

In [17]:
top_data_of_killed = person_of_killed.groupby('CONTRIBUTING FACTORS').nlargest(5).reset_index(level=0, drop=True)
top_data_of_killed = top_data_of_killed.reset_index()

top_data_of_killed.sort_values('NUMBER OF PERSONS KILLED',ascending=False).head(5)

              CONTRIBUTING FACTORS  NUMBER OF PERSONS KILLED
37                     Unspecified                    1750.0
3   Driver Inattention/Distraction                     268.0
9    Failure to Yield Right-of-Way                     189.0
33     Traffic Control Disregarded                     182.0
36                    Unsafe Speed                     156.0

##### Tabela przedstawia 5 najczęstsze przyczyny wypadków, w których jest najwięcej ofiar śmiertelnych

## Podsumowanie

## Po przeanalizowaniu danych wejściowych - najwięcej osób śmiertelnych występuje w wypadkach spowodowanymi:
### 1. Nieokreślone - 1750 ofiar
### 2. Nieuwaga/rozproszenie kierowcy - 268 ofiar
### 3. Nieustąpienie pierwszeństwa przejazdu - 189 ofiar
### 4. Przejazd na czerwonym świetle - 182 ofiary
### 5. Nadmierna prędkość - 156 ofiar